# Generated by Django 3.1.7 on 2022-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagem do Evento')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Evento')),
                ('startTime', models.DateTimeField(verbose_name='Horário de Início')),
                ('endTime', models.DateTimeField(verbose_name='Horário de Término')),
                ('locationName', models.CharField(max_length=255, verbose_name='Nome do Local')),
                ('locationUrl', models.CharField(max_length=1024, verbose_name='Website do Local')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('details', models.CharField(max_length=255, verbose_name='Detalhes')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
