# Generated by Django 3.1.7 on 2022-03-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='address',
            field=models.CharField(max_length=1024, verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='events',
            name='details',
            field=models.TextField(verbose_name='Detalhes'),
        ),
    ]
