# Generated by Django 3.1.7 on 2022-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(blank=True, default=True, null=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galeria de Fotos',
            },
        ),
    ]
