# Generated by Django 3.1.7 on 2022-03-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20220310_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Boletim Semanal', 'verbose_name_plural': 'Boletim Semanal'},
        ),
    ]
