# Generated by Django 3.1.7 on 2022-03-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('speaker', models.CharField(max_length=255, verbose_name='Orador')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('link', models.CharField(max_length=1024, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Sermão',
                'verbose_name_plural': 'Sermões',
            },
        ),
    ]
