# Generated by Django 3.1.7 on 2022-03-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(default=123, upload_to='sermon/', verbose_name='Thumbnail'),
            preserve_default=False,
        ),
    ]
