# Generated by Django 3.1.7 on 2022-02-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='textoRodape',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Texto Rodapé'),
        ),
    ]
