# Generated by Django 3.1.7 on 2022-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_config_textorodape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='textoRodape',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Rodapé'),
        ),
    ]
