# Generated by Django 3.1.7 on 2022-02-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='site',
        ),
    ]
