# Generated by Django 3.1.7 on 2022-02-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('home', '0006_remove_banner_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeiraSecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone1', models.CharField(max_length=255, verbose_name='Ícone 1')),
                ('titulo1', models.CharField(max_length=255, verbose_name='Título 1')),
                ('subtitulo1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitulo 1')),
                ('texto1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto 1')),
                ('icone2', models.CharField(max_length=255, verbose_name='Ícone 2')),
                ('titulo2', models.CharField(max_length=255, verbose_name='Título 2')),
                ('subtitulo2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitulo 2')),
                ('texto2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto 2')),
                ('icone3', models.CharField(max_length=255, verbose_name='Ícone 3')),
                ('titulo3', models.CharField(max_length=255, verbose_name='Título 3')),
                ('subtitulo3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitulo 3')),
                ('texto3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto 3')),
                ('servicesTitulo', models.CharField(max_length=255, verbose_name='Título Serviço (quadro direito)')),
                ('servicesSubtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitulo Serviço (quadro direito)')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Primeira Seção',
                'verbose_name_plural': 'Primeira Seção',
            },
        ),
    ]
