# Generated by Django 3.1.7 on 2022-02-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_primeirasecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primeirasecao',
            name='texto1',
            field=models.CharField(default=123, max_length=255, verbose_name='Texto 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='primeirasecao',
            name='texto3',
            field=models.CharField(default=123, max_length=255, verbose_name='Texto 3'),
            preserve_default=False,
        ),
    ]
