# Generated by Django 3.1.7 on 2022-02-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('home', '0008_auto_20220228_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primeirasecao',
            options={'verbose_name': 'Seção 1', 'verbose_name_plural': 'Seção 1'},
        ),
        migrations.CreateModel(
            name='SegundaSecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Imagem de Fundo')),
                ('upperText', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Superior')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('texto', models.TextField(default='', verbose_name='Texto')),
                ('botaoLink', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link do Botão')),
                ('botaoText', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto do Botão')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Seção 2',
                'verbose_name_plural': 'Seção 2',
            },
        ),
    ]
