# Generated by Django 3.1.7 on 2022-02-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('home', '0009_auto_20220228_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerceiraSecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('dado1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome 1')),
                ('valor1', models.IntegerField(blank=True, default=1, null=True, verbose_name='Valor 1')),
                ('dado2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome 2')),
                ('valor2', models.IntegerField(blank=True, default=1, null=True, verbose_name='Valor 2')),
                ('dado3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome 3')),
                ('valor3', models.IntegerField(blank=True, default=1, null=True, verbose_name='Valor 3')),
                ('dado4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome 4')),
                ('valor4', models.IntegerField(blank=True, default=1, null=True, verbose_name='Valor 4')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Seção 3',
                'verbose_name_plural': 'Seção 3',
            },
        ),
    ]
