# Generated by Django 3.1.7 on 2022-03-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Título')),
                ('cargo', models.CharField(max_length=255, verbose_name='Título')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pastor/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Pastor',
                'verbose_name_plural': 'Pastor',
            },
        ),
        migrations.CreateModel(
            name='AboutTerceiraSecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('dado1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome 1')),
                ('valor1', models.IntegerField(blank=True, default=1, null=True, verbose_name='Valor 1')),
                ('dado2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome 2')),
                ('valor2', models.IntegerField(blank=True, default=1, null=True, verbose_name='Valor 2')),
                ('dado3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome 3')),
                ('valor3', models.IntegerField(blank=True, default=1, null=True, verbose_name='Valor 3')),
                ('dado4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome 4')),
                ('valor4', models.IntegerField(blank=True, default=1, null=True, verbose_name='Valor 4')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Seção 3',
                'verbose_name_plural': 'Seção 3',
            },
        ),
        migrations.CreateModel(
            name='AboutSegundaSecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Imagem de Fundo')),
                ('upperText', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Superior')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('texto', models.TextField(default='', verbose_name='Texto')),
                ('botaoLink', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link do Botão')),
                ('botaoText', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto do Botão')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Seção 2',
                'verbose_name_plural': 'Seção 2',
            },
        ),
        migrations.CreateModel(
            name='AboutPrimeiraSecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone1', models.CharField(max_length=255, verbose_name='Ícone 1')),
                ('titulo1', models.CharField(max_length=255, verbose_name='Título 1')),
                ('subtitulo1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitulo 1')),
                ('texto1', models.CharField(max_length=255, verbose_name='Texto 1')),
                ('icone2', models.CharField(max_length=255, verbose_name='Ícone 2')),
                ('titulo2', models.CharField(max_length=255, verbose_name='Título 2')),
                ('subtitulo2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitulo 2')),
                ('texto2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto 2')),
                ('icone3', models.CharField(max_length=255, verbose_name='Ícone 3')),
                ('titulo3', models.CharField(max_length=255, verbose_name='Título 3')),
                ('subtitulo3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitulo 3')),
                ('texto3', models.CharField(max_length=255, verbose_name='Texto 3')),
                ('servicesTitulo', models.CharField(max_length=255, verbose_name='Título Serviço (quadro direito)')),
                ('servicesSubtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitulo Serviço (quadro direito)')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Seção 1',
                'verbose_name_plural': 'Seção 1',
            },
        ),
    ]
