# Generated by Django 3.1.7 on 2022-03-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastor',
            name='cargo',
            field=models.CharField(max_length=255, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
