# Generated by Django 3.1.7 on 2022-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testemunho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testemunho/', verbose_name='Image')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('shortDescription', models.CharField(max_length=255, verbose_name='Descrição Curta')),
                ('description', models.TextField(verbose_name='Testemunho')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL do vídeo do Testemunho (Youtube)')),
            ],
        ),
    ]
